# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='supplier',
            name='area',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='supplier',
            name='license',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='supplier',
            name='location',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='supplier',
            name='name',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='supplier',
            name='phone',
            field=models.TextField(default=''),
        ),
    ]
