# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_auto_20170617_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='area',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='license',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='location',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(default='', max_length=20),
        ),
    ]
