# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 13:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='标题')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('status', models.CharField(default='待确认', max_length=10, verbose_name='状态')),
                ('offer_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='成交价格')),
                ('initiator', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='clients.Purchaser', verbose_name='发起人')),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='stocks.Product')),
                ('supplier', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.Supplier', verbose_name='制定供应商')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(default='', max_length=20, verbose_name='数量')),
                ('purchase_order', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='deals.PurchaseOrder')),
                ('purchaser', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='clients.Purchaser')),
            ],
        ),
        migrations.CreateModel(
            name='SupplyOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='报价')),
                ('offer_amount', models.CharField(default=0, max_length=10)),
                ('is_updated', models.BooleanField(default=True)),
                ('is_noticed', models.BooleanField(default=False)),
                ('purchase_order', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='deals.PurchaseOrder')),
                ('supplier', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='clients.Supplier')),
            ],
        ),
    ]
