# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 06:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchaser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
                ('phone', models.CharField(default='', max_length=20)),
                ('address', models.CharField(default='', max_length=100)),
                ('location', models.CharField(default='', max_length=20)),
                ('license', models.CharField(default='', max_length=20)),
                ('area', models.CharField(default='', max_length=20)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
