# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 07:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20170629_0739'),
        ('clients', '0003_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='postprice',
            name='amount',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='postprice',
            name='price',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='postprice',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
        migrations.AddField(
            model_name='postprice',
            name='supplier',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='clients.Supplier'),
        ),
    ]
