# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 13:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20, verbose_name='名称')),
                ('image', models.CharField(default='', max_length=20, verbose_name='图片')),
                ('category', models.CharField(default='', max_length=20, verbose_name='类型')),
                ('location', models.CharField(default='', max_length=20, verbose_name='地区')),
                ('amount', models.CharField(default='', max_length=20, verbose_name='采购数量')),
                ('purchaser', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='clients.Purchaser')),
            ],
        ),
    ]
