# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 01:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PreOrder',
            new_name='PurchaseOrder',
        ),
        migrations.RenameModel(
            old_name='PreOrderLine',
            new_name='PurchaseOrderLine',
        ),
    ]
