# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 07:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postprice',
            name='product',
        ),
        migrations.DeleteModel(
            name='PostPrice',
        ),
    ]
