# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 06:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='supplier',
            new_name='purchaser',
        ),
    ]
