# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 01:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20170702_0140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorderline',
            name='product',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
    ]
