# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 05:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20170702_0138'),
        ('products', '0005_purchaseorder_initiator'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOfferLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(default=0, max_length=20, verbose_name='报价')),
                ('offer_amount', models.CharField(default=0, max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='initiator',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='clients.Purchaser', verbose_name='发起人'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='amount',
            field=models.CharField(default='', max_length=20, verbose_name='数量'),
        ),
        migrations.AddField(
            model_name='purchaseofferline',
            name='purchase_order',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='products.PurchaseOrder'),
        ),
        migrations.AddField(
            model_name='purchaseofferline',
            name='supplier',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='clients.Supplier'),
        ),
    ]
