# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 11:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20170702_0138'),
        ('products', '0007_auto_20170702_0603'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='offer_price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='成交价格'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.Supplier', verbose_name='制定供应商'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(default='待确认', max_length=10, verbose_name='状态'),
        ),
    ]
