# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20170702_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseofferline',
            name='price',
            field=models.IntegerField(default=0, verbose_name='报价'),
        ),
    ]
