# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20170702_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseofferline',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='报价'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='offer_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='成交价格'),
        ),
    ]
